# Generated by Django 5.0.6 on 2024-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orders_order_date_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
